# Generated by Django 5.2.13 on 2026-06-13 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_constructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_username', models.SlugField()),
                ('direction', models.SmallIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_votes', to='articles_constructor.article')),
            ],
            options={
                'db_table': 'article_votes',
                'unique_together': {('article', 'voter_username')},
            },
        ),
    ]
