# Generated by Django 6.0.3 on 2026-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles_constructor', '0002_add_article_vote'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='article_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['author_username', 'status'], name='article_author_status_idx'),
        ),
    ]
