# Generated by Django 6.0.3 on 2026-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0003_rename_company_username_to_owner_username'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status'], name='test_status_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['owner_username', 'status'], name='test_owner_status_idx'),
        ),
    ]
