# Generated by Django 6.0.3 on 2026-09-14 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_test_test_status_idx_test_test_owner_status_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_username', models.SlugField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='constructor.test')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['test', 'finished_at'], name='attempt_test_finished_idx'), models.Index(fields=['test', '-started_at'], name='attempt_test_started_idx')],
            },
        ),
    ]
