# Generated by Django 5.2.13 on 2026-07-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('article', 'Статья'), ('user', 'Пользователь'), ('company', 'Компания'), ('contest', 'Конкурс'), ('test', 'Тест')], max_length=20)),
                ('target_id', models.CharField(max_length=100)),
                ('target_title', models.CharField(max_length=255)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('author_username', models.SlugField(blank=True)),
                ('reporter_username', models.SlugField(blank=True)),
                ('reason', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('resolved', 'Рассмотрена'), ('dismissed', 'Отклонена')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
