# Generated by Django 6.0.3 on 2026-09-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('reporter_username', 'target_type', 'target_id'), name='unique_report_per_reporter'),
        ),
    ]
