# Generated by Django 5.2.13 on 2026-07-21 22:19

from django.db import migrations, models


def approve_existing_verified(apps, schema_editor):
    """Компании, у которых уже загружен документ, раньше считались подтверждёнными
    (is_verified = bool(document)). Сохраняем им статус 'approved', чтобы не пропали из каталога."""
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.exclude(registration_document=''):
        company.verification_status = 'approved'
        company.submitted_at = company.created_at
        company.verified_at = company.created_at
        company.save(update_fields=['verification_status', 'submitted_at', 'verified_at'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('none', 'Документ не загружен'), ('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(approve_existing_verified, noop_reverse),
    ]
