# Generated by Django 6.0.3 on 2026-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название направления')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='direction_1',
        ),
        migrations.RemoveField(
            model_name='company',
            name='direction_2',
        ),
        migrations.RemoveField(
            model_name='company',
            name='direction_3',
        ),
        migrations.RemoveField(
            model_name='company',
            name='direction_4',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Отображаемое имя'),
        ),
        migrations.AddField(
            model_name='company',
            name='directions',
            field=models.ManyToManyField(blank=True, related_name='companies', to='main.direction', verbose_name='Направления'),
        ),
    ]
