# Generated by Django 6.0.3 on 2026-03-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_company_directions_company_directions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direction',
        ),
    ]
