# Generated by Django 6.0.3 on 2026-03-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_direction_remove_company_directions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='directions',
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.AddField(
            model_name='company',
            name='directions',
            field=models.CharField(blank=True, max_length=500, verbose_name='Основные направления'),
        ),
    ]
