# Generated by Django 6.0.3 on 2026-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_company_directions_delete_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='directions',
        ),
        migrations.AddField(
            model_name='company',
            name='direction_1',
            field=models.CharField(blank=True, max_length=120, verbose_name='Направление 1'),
        ),
        migrations.AddField(
            model_name='company',
            name='direction_2',
            field=models.CharField(blank=True, max_length=120, verbose_name='Направление 2'),
        ),
        migrations.AddField(
            model_name='company',
            name='direction_3',
            field=models.CharField(blank=True, max_length=120, verbose_name='Направление 3'),
        ),
        migrations.AddField(
            model_name='company',
            name='direction_4',
            field=models.CharField(blank=True, max_length=120, verbose_name='Направление 4'),
        ),
    ]
