# Generated by Django 5.2.13 on 2026-07-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ban_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='ban_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('warned', 'Предупреждён'), ('banned', 'Забанен')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='warning_reason',
            field=models.TextField(blank=True),
        ),
    ]
