# Generated by Django 6.0.3 on 2026-09-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_account_ban_reason_account_ban_until_account_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
