# Generated by Django 6.0.3 on 2026-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_account_django_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('user', 'Кандидат'), ('company', 'Компания'), ('moderator', 'Модератор')], default='company', max_length=32),
        ),
    ]
