# Generated by Django 6.0.3 on 2026-09-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_account_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='warned_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='warning_reason',
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('banned', 'Забанен')], db_index=True, default='active', max_length=20),
        ),
    ]
