# Generated by Django 5.2.13 on 2026-07-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_username', models.SlugField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('case_text', models.TextField(blank=True)),
                ('rules', models.JSONField(default=list)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('prize', models.CharField(blank=True, max_length=255)),
                ('submission_type', models.CharField(default='file', max_length=10)),
                ('submission_hint', models.TextField(blank=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('participants_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'contests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contest_attachments/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(default=0)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contests_cabinet.contest')),
            ],
            options={
                'db_table': 'contest_attachments',
            },
        ),
        migrations.CreateModel(
            name='ContestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_username', models.SlugField()),
                ('candidate_name', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, upload_to='contest_submissions/')),
                ('link', models.URLField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('liked', models.BooleanField(default=False)),
                ('winner', models.BooleanField(default=False)),
                ('attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contests_cabinet.contest')),
            ],
            options={
                'db_table': 'contest_submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
