# Generated by Django 6.0.3 on 2026-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests_cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['status'], name='contest_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contest',
            index=models.Index(fields=['company_username', 'status'], name='contest_company_status_idx'),
        ),
    ]
