# Generated by Django 6.0.3 on 2026-09-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
